# WUD watches floating tags by digest and automatically applies each new image.

services:
  vaultwarden:
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$$"
      - "wud.trigger.include=smtp.gmail,docker.local"
  backvault:
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$$"
      - "wud.trigger.include=smtp.gmail,docker.local"
