# https://hub.docker.com/r/linuxserver/lidarr

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK}

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-media}-lidarr
    hostname: ${CONTAINER_NAME_PREFIX:-media}-lidarr
    restart: always
    networks:
      - default
    volumes:
      - ${VOLUMES_BASE:-/tmp}/${CONTAINER_NAME_PREFIX:-media}/containers/lidarr:/config
      - ${MEDIA_PATH}:/media
    ports:
      - ${LIDARR_HTTP_PORT:-8686}:8686
    environment:
      <<: *base-env
    depends_on:
      - prowlarr
    labels:
      - "com.service=${CONTAINER_NAME_PREFIX:-media}-lidarr"